prefer signed commit over unsigned, added fallback

diff --git a/scripts/gac b/scripts/gac
--- a/scripts/gac
+++ b/scripts/gac
@@ -8,4 +8,9 @@ if [ "$PARAMS" == "" ]; then
 fi
 
 git add .
-git commit -S -m "$PARAMS"
+if ! git commit -S -m "$PARAMS"; then
+    echo -e "Failed to sign commit, using unsigned commit instead."
+    if ! git commit -S -m "$PARAMS"; then
+        echo -e "Failed to commit, aborting."
+    fi
+fi
